# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b111a3f34f8b64055c74287493c93dff58e83c3dba7517c4bdf95ecab47042144410c952011836f68ac2793e8690106e86e83a5a2bdabd276ef605505186d97

test:
  secret_key_base: 42ac2da67ab7eff6887b6f3e8c76d020c44209b9d150ad658185fe8b01ea41bff029ed274c61f8ad0a7c77004336ef41eefccf453ecbcfaf1a42d3c6f8db0058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
